// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;
import service1.service2;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    // Fetches the current catalog from service2, paginating through `limit`/
    // `offset`/`next` as needed, and returns the integer average of every
    // record's score. The contract documents only one 200 response, so an
    // empty catalog (recordCount=0) reports an average of 0 rather than
    // erroring — there is no error schema to surface a failure through.
    resource function get average\-score() returns AverageScore|error {
        int totalScore = 0;
        int recordCount = 0;
        int pageOffset = 0;
        final int pageLimit = 20;
        boolean morePages = true;
        while morePages {
            service2:inline_response_200 catalogPage = check serviceTwoClient->/catalog.get(offset = pageOffset, 'limit = pageLimit);
            service2:Record[] pageRecords = catalogPage.data;
            foreach service2:Record catalogRecord in pageRecords {
                totalScore += catalogRecord.score;
            }
            recordCount += pageRecords.length();
            string? nextPage = catalogPage?.next;
            if nextPage is () {
                morePages = false;
            } else {
                pageOffset += pageLimit;
            }
        }
        log:printInfo("average score request handled", recordCount = recordCount);
        int averageScore = recordCount == 0 ? 0 : totalScore / recordCount;
        return {average: averageScore};
    }

    // Catch-all for any path/method this service does not serve — a
    // structured 404, distinct from the documented /average-score response.
    resource function 'default [string... requestPath]() returns http:NotFound {
        string joinedPath = "/" + string:'join("/", ...requestPath);
        ApiError errorBody = {
            code: 404,
            message: "Not Found",
            description: string `No resource exists for the path '${joinedPath}'`
        };
        return <http:NotFound>{body: errorBody};
    }
}

public type AverageScore record {
    # Sum of every record's score divided by the record count, discarding any remainder
    int average;
};

# Structured body for a request to a path this service does not serve —
# distinct from the documented AverageScore response.
type ApiError record {|
    int code;
    string message;
    string description;
|};
