// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The current catalog of scored records
    #
    # + return - The records in the current catalog
    resource function get catalog(int 'limit = 20, int offset = 0) returns inline_response_200 {
        int effectiveLimit = 'limit;
        if effectiveLimit > 100 {
            effectiveLimit = 100;
        }
        if effectiveLimit < 0 {
            effectiveLimit = 0;
        }
        int effectiveOffset = offset;
        if effectiveOffset < 0 {
            effectiveOffset = 0;
        }

        Record[] allRecords = currentCatalog();
        int total = allRecords.length();

        int endIndex = effectiveOffset + effectiveLimit;
        if endIndex > total {
            endIndex = total;
        }

        Record[] pageRecords = [];
        if effectiveOffset < total {
            pageRecords = allRecords.slice(effectiveOffset, endIndex);
        }

        string? next = ();
        if endIndex < total {
            next = string `/catalog?limit=${effectiveLimit}&offset=${endIndex}`;
        }

        string? previous = ();
        if effectiveOffset > 0 {
            int prevOffset = effectiveOffset - effectiveLimit;
            if prevOffset < 0 {
                prevOffset = 0;
            }
            previous = string `/catalog?limit=${effectiveLimit}&offset=${prevOffset}`;
        }

        log:printInfo("catalog request handled", recordCount = pageRecords.length());

        return {
            count: total,
            next: next,
            previous: previous,
            data: pageRecords
        };
    }

    resource function post internal/catalog\-mode(@http:Payload internal_catalogmode_body payload) returns InlineResponse2001Ok|ErrorBadRequest {
        string mode = payload.mode;
        if mode != "full" && mode != "empty" {
            return <ErrorBadRequest>{
                body: {
                    code: 400,
                    message: "Invalid mode value",
                    description: string `mode must be 'full' or 'empty', received '${mode}'`
                }
            };
        }

        setCatalogMode(mode);

        if mode == "full" {
            return <InlineResponse2001Ok>{body: {mode: "full"}};
        }
        return <InlineResponse2001Ok>{body: {mode: "empty"}};
    }
}

public type internal_catalogmode_body record {|
    string mode;
|};

public type InlineResponse2001Ok record {|
    *http:Ok;
    inline_response_200_1 body;
|};

public type inline_response_200_1 record {
    "full"|"empty" mode;
};

public type inline_response_200 record {
    # total matching records
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Record[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type Record record {
    # record identifier
    int id;
    # record name
    string name;
    # record score
    int score;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};
